version: '3.9'
services: 
  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    volumes: 
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      ELASTIC_PASSWORD: 91?JComEt+mvz%T
      discovery.type: single-node
    networks: 
      - elk
  kibana:
    container_name: kibana
    restart: always
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports: 
      - 5601:5601
    networks: 
      - elk
    depends_on: 
      - elasticsearch
  apm:
    container_name: apm
    restart: always
    image: docker.elastic.co/apm/apm-server:$ELK_VERSION
    volumes: 
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    command: 
      - --strict.perms=false
    ports: 
      - 8200:8200
    networks: 
      - elk
    depends_on: 
      - elasticsearch
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - elk
    depends_on: 
      - kibana
      - apm

networks: 
  elk:
    driver: bridge

volumes: 
  elasticsearch: